wiki_general_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: WikiGeneralBundle:Default:index }


_wiki:
    resource: "@WikiGeneralBundle/Controller/DefaultController.php"
    type:     annotation
