parameters:
#    wiki_general.example.class: Wiki\GeneralBundle\Example

services:
#    wiki_general.example:
#        class: %wiki_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
