parameters:
#    wiki_general.example.class: Wiki\GeneralBundle\Example

services:
    acme_demo.form.type.task:
        class: Wiki\GeneralBundle\Form\Type\PageType
        tags:
            - { name: form.type, alias: page }
